### ISSUE TITLE
Streamlink and settings for it probably don't work

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#146]

**Comment by pajlada** [comment]
Streamlink has basic functionality, the "choose" setting just doesn't work as expected imo but maybe I just don't know how it's supposed to work.
I restructured the code a bit in ef9aedb2cdc50889470f8938c0e7f15a91ff7571 to easier give some console error messages in case the path is wrong.

**Comment by Confuseh** [comment]
So the issue with the "choose" not working might be due to `default-stream=<quality>` being used [in config], since it relies on the last line starting with "Available streams" that gets printed to stdout, when no quality and no `--default-stream` are specified.
There is no simple ways to prevent this, since streamlink does not include an option just to show quality options. It is possible to add `--default-stream someinvalidbullshithere` to force an error, but then "Available streams" part is indented [ I guess can be resolved with a trim ].
