### ISSUE TITLE
More fluent flow on creating tabs

### ISSUE THREAD

**Issue by ThePridestalker** [fourtf/chatterino2#214]
Atm if you make a new tab you have to click the new frame to write the name of the channel you want to join in the small window. That part should be more fluent. Opening the tab and instantly getting the popup to write the name of the channel would be a possibility but if you opened it by mistake I dont think you can close it without mouse.

Writing the name of the channel in the new frame should be faster, in case of making it by mistake you can close it with contrl + W without using the mouse.

Write a better idea if you make it up.

**Comment by fourtf** [comment]
I don't want to open the tab instantly as it a) is currently used to teach the user some actions and b) since it might break the users flow (e.g. creating a tab just to drag other splits in).

I can however enable Ctrl+T to work on the newly created tab which would also make the process of adding a tab more fluent. (Ctrl+Shift+T could be used to instantly show the channel dialog)
