### ISSUE TITLE
Feature Requests for Chatterino

### ISSUE THREAD

**Issue by Artiiz** [fourtf/chatterino2#33]
- Ability to view messages typed by a viewer (by clicking on user and seeing the early messages).
- Being able to move the userpanel of when you click on a user in a specific channel.
- To have a viewerlist of who is in the specified channel (For example an on/off function in the right of the chat).
- Being able to change the color of links typed in chat (I would really like them to be blue instead of grey ish).
- Able to like Favorite specific emotes so that they're priority 1 in using emotes (either in the Emotes List or throughout chat).
- Being able to edit the time of Timeout Buttons in the userpanele by clicking on a viewer.

I think this is everything I can come up with now, I really love the project and would definitely use it if some of these features were put in it.
Thank you,

Best regards
- Artiiz

**Comment by fourtf** [comment]
Should all be able to be added after I finish my exams 👍

**Comment by Artiiz** [comment]
Awesome, greatful to hear 👍

**Comment by fourtf** [comment]
- added to the user info popup https://github.com/fourtf/chatterino2/issues/18
- I'll add it when it starts triggering me too much
- already added
- probably just gonna be blue now anyways
- doesn't seem like a necessarity
- too specific setting -> goal of chatterino is to provide settings for everything important, not for features that 2 people use -> proper defaults are required instead of custom timeout amounts

**Comment by pajlada** [comment]
> I want to see the section of my favorite emoticons, so as not to search for my emoticon in all sections
> :)

This issue isn't a 'catch-all' place to report new issues, rather use the "New issue" in the top-right and follow the available templates. Make sure you've [searched for your issues](https://github.com/Chatterino/chatterino2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) before though.

Locking this issue.
