### ISSUE TITLE
Some Features to add pajaDank

### ISSUE THREAD

**Issue by ThePridestalker** [fourtf/chatterino2#35]
-Any kind of previsualization on hovering the mentions marks in the scroll bar. ( it can look like when hovering an emote ) and also making it clickable to move me directly to that line instead of scrolling ?

-When presing control + T and opening a new split, the window asking for channel name instantly appears. When I click the plus button to add a new channel i have to click again in the panel to open that window to write the channel name <img src="https://cdn.betterttv.net/emote/5738dc6ad7a0b60d147270a0/1x">

-Also if you choose that you are mistaken and want to close the window, the tab will be still there saying " empty " with no channel. Should be removed if the person clicks the cancel / X button.

-When clicking over the name of someone you get a small window showing info about them, make it draggable.

-When the streamer goes live, the name of the room will say his < name (live) > but you dont really notice that because you look at the bottom part of the screen. Maybe adding 🔴  at the left of the channel name would be great (dont remove the live parenthesis ) 

Nice work buddy <img src="https://cdn.betterttv.net/emote/568d840001ea6722348ab018/1x">

**Comment by fourtf** [comment]
- sounds interesting, will open a new issue since this is a collection of issues (rel https://github.com/fourtf/chatterino2/issues/109 )
- not really an issue right now since there is no "new tab" hotkey anyways so you are already at your mouse, will consider it when I add a hotkey for it (rel https://github.com/fourtf/chatterino2/issues/21 )
- minor issue and could be confusing when trying to open an empty split
- added, not gonna be dragable for now tho xd
- I can see it just fine
