### ISSUE TITLE
Crash when attemping to open logs

### ISSUE THREAD

**Issue by fruzitent** [fourtf/chatterino2#579]
If I select viewers or moderators, I get an error message that they are missing. If I select the broadcasters logs, I will also receive an error message, but if I select them again, the application crashes

![screenshot_3](https://user-images.githubusercontent.com/40008647/42409041-f7b22d08-81dc-11e8-9d78-69ace6710b1f.png)
![screenshot_4](https://user-images.githubusercontent.com/40008647/42409042-f7d6b6e6-81dc-11e8-874d-04c05f422d36.png)
![screenshot_5](https://user-images.githubusercontent.com/40008647/42409043-f7f3b0b6-81dc-11e8-8239-53a6d35f54a6.png)
![screenshot_6](https://user-images.githubusercontent.com/40008647/42409044-f8114cde-81dc-11e8-9ea0-ba9720b1ddf0.png)
![screenshot_7](https://user-images.githubusercontent.com/40008647/42409045-f82f4fd6-81dc-11e8-9250-a6cbb210472a.png)

Problem Event Name: APPCRASH
Application Name: chatterino.exe
Application Version: 0.0.0.0
Application Timestamp: 5b406fa0
Fault Module Name: Qt5Widgets.dll
Fault Module Version: 5.11.1.0
Fault Module Timestamp: 5b234b76
Exception Code: c0000005
Exception Offset: 0000000000017fad
OS Version: 6.1.7601.2.1.0.256.1
Locale ID: 1049
Additional information 1: a111
Additional information 2: a111f32ddfc05af6f45b9b3976c0d5de
Additional information 3: 87cf
Additional information 4: 87cfb5b57b8840dc6ae5bde2f47ad99e

**Comment by fruzitent** [comment]
and return the tab control back to the left 😡

**Comment by DatGuy1** [comment]
`If I select viewers or moderators, I get an error message that they are missing. If I select the broadcasters logs, I will also receive an error message`
That's just because pajlada does have logviewer enabled but has it hidden

`but if I select them again, the application crashes`
Probably something line 71-73

`and return the tab control back to the left or make sure that the drop-down box does not go beyond the limits of the program 😡`
3 issues open about it already
