### ISSUE TITLE
Reload Emotes button doesn't reload emotes

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#595]
Title pretty much
This bug exists in the latest commit as of now: 91e320e
Doesn't happen in the latest Beta 2.0.4. Happens on both FFZ and BTTV emotes.

Steps to reproduce:
1. Add new emote in your channel
2. Press reload channel emotes
3. Emote is there but Chatterino doesn't tab-complete it or see it
Same happens when you remove an emote.
Cache issue?

I have a small workaround for now: Open Chatterino Beta, load the new channel emotes, exit, open latest nightly and new channel emotes are now loaded.

**Comment by LajamerrMittesdine** [comment]
I have to delete %APPDATA%/Chatterino 2/Cache

**Comment by pajlada** [comment]
the error is because I enabled caching of the APIs, with no expiration date
https://github.com/fourtf/chatterino2/blob/master/src/providers/ffz/FfzEmotes.cpp#L52
https://github.com/fourtf/chatterino2/blob/master/src/providers/ffz/FfzEmotes.cpp#L95
https://github.com/fourtf/chatterino2/blob/master/src/providers/bttv/BttvEmotes.cpp#L27
https://github.com/fourtf/chatterino2/blob/master/src/providers/bttv/BttvEmotes.cpp#L71

if someone can PR to remove those lines that'd be nice
