### ISSUE TITLE
Lagging causing me not be able to send messages

### ISSUE THREAD

**Issue by lanes100** [fourtf/chatterino2#619]
In streams with high chat activity, my chat will stop every 10 or 15 seconds and if i try to send a message within the small 2 seconds when it is stopped, it doesn't send the message.

**Comment by lanes100** [comment]
I don't get that when I'm in regular twitch chat on their website.

**Comment by notheowner** [comment]
Browser chat behaves differently, what you send in browser chat doesn't mean it always goes through.
You could see it as sent on your side but in reality it never reached the chat room.

The short period that you see the chat "freezing" exists in browser chat as well, because browser chat handles messages pace differently, you don't really see it.

For example, try sending a message in browser chat in a chat you are banned/timed out.
You see the message appear in the chat room but in reality it never reached the chat room

Example: 
![2018-07-15_18-40-29](https://user-images.githubusercontent.com/25968992/42735545-b3cbb87e-885e-11e8-8ef0-31b79c4b7579.gif)
