### ISSUE TITLE
FrankerFaceZ (FFZ) emotes are not loading

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#709]
nightly v1.0.717 built 2018-09-17T10:51:16.0000000Z

![grafik](https://user-images.githubusercontent.com/16636423/45638494-a4b16d80-baad-11e8-82e1-9d9270b7fde1.png)

**Comment by pajlada** [comment]
To clarify upon this issue: Global FFZ emotes work, but FFZ channel emotes only sometimes work. This could be due to rate-limiting, us consuming the API improperly. The API call could also be really delayed, so we might wanna look into setting a reasonable timeout on the request.

**Comment by RAnders00** [comment]
I did some analysis on this issue since it also affected me. I watched the network traffic in procmon to find out and behavioural differences between the case where it loads FFZ on startup successfully and the case where it fails to load.

A normal startup looks like this:
![success](https://user-images.githubusercontent.com/1629196/45640617-72a30a00-bab3-11e8-9a46-9d2e8dac3a44.png)
Note all the network requests are all within a short timespan of a few hundred milliseconds.

A startup which fails to load looks like this:
![failure](https://user-images.githubusercontent.com/1629196/45640684-97977d00-bab3-11e8-92a5-6908ad9a9cdd.png)
Note there is a break in the network requests, it seems like the second batch of requests is issued after something else happens in the application (logs are loaded maybe?)

Replicating this issue also seems to depend on your peer FFZ server to some degree. In my short testing I could only replicate the issue with IPv4 servers (IP is in the screenshot), whilst with the v6 servers my emotes always loaded fine. (Could just be a load/timing difference between them though, instead of an issue directly stemming from the difference between v4 and v6)

Raw Procmon captures are here:  
https://cloud.zwb3.de/s/PKWLFgorRgqDEQK success.pml  
https://cloud.zwb3.de/s/bPdgmwn6ioKpXSa failure.pml
