### ISSUE TITLE
Account manager/switcher

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#9]

**Comment by pajlada** [comment]
Initial work done in 467ca90fd8630e800cc7f87e2f4c27cb3a115ce3 - requires some refining

Account switching, for example, is not implemented at all

**Comment by pajlada** [comment]
Implement live account-switching in a372bae80ddaea3aa95481425ba2195ece34b0ac
No messages for when the irc connection is disconnected/connected are currently visible, so that should be something we want to add too.
IRC Connecting is no longer done in an async thread - I didn't notice any drawbacks to removing the asynchronous call so I will just leave it for now. As described in the commit message, the reason I removed the asynchronous call was that the irc connections need to be closed from the same thread that opened it which is not guaranteed with the asynchronous thread pool

**Comment by pajlada** [comment]
Added the disconnected from chat/connected to chat messages in commit 87203c11203e9a80f75907b22c6858d3ec5bdc14

Changed the way connections are created/deleted in b13b8a2ce6fa4088f59f705493d4902e3e4128d0
They're now only created once upon application start, and then reused upon reconnecting. Only downside to doing it like this is that we can't have two read connections simultaneously while switching user so no messages are missed, but that's not a feature Chatterino1 has right now so I'm not going to spend time implementing that.

**Comment by pajlada** [comment]
I think what's left is making sure that the account connection is made smoothly so no Chatterino restart is required.

**Comment by pajlada** [comment]
- [ ] Implement removing of saved accounts (Remember to add special case for the anonymous user)
 - [ ] Ensure that the process of adding accounts is smooth
 - [ ] Make it so you cannot unselect things in the AccountSwitchWidget
